name: moalem
description: "Moalem"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  go_router: ^17.0.0
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.6.1
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  sqflite: ^2.4.2
  shared_preferences: ^2.5.4
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^4.2.1
  flutter_animate: ^4.5.2
  dio: ^5.9.0
  retrofit: ^4.9.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.2.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.2.3
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  injectable_generator: ^2.6.2
  flutter_native_splash: ^2.4.7
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AdobeArabic
      fonts:
        - asset: assets/fonts/adobe-arabic-regular.otf
          weight: 400
        - asset: assets/fonts/adobe-arabic-italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/adobe-arabic-bold.otf
          weight: 700
        - asset: assets/fonts/adobe-arabic-bold-italic.otf
          weight: 700
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
